name: Basic test on PR
on:
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action on PR
    steps:
      - uses: actions/checkout@v2
      - name: test new issue
        uses: DanielBarnes/create-issue-action@${{ github.sha }}
        with:
          token: ${{ github.token }}
          title: Simple test issue
          body: |
            This is a test that includes
            a multiline string.
          assignees: DanielBarnes
