name: Basic Tests
on:
  pull_request:
    branches: main
  workflow_dispatch:
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --silent --show-error \
            --request POST \
            --header "Authorization: token ${{ secrets.PAT }}" \
            --header "Accept: application/vnd.github.v3+json" \
            --url "https://api.github.com/repos/dacbd/err/dispatches" \
            --data '{"event_type":"basic", "client_payload": {"key":"value", "ref_name":"${{ github.ref_name }}"} }'
